import { StyleSheet } from 'react-native';

export const NeoOutdoors = {
  color: {
    electricCyan: '#22F3FF',
    deepCyan: '#0891B2',
    adventurePink: '#FF3EA5',
    sunsetAmber: '#F59E0B',
    roseGlow: '#FB7185',
    ink: '#0B1220',
    inkSoft: '#0F172A',
    slate: '#475569',
    slateMuted: '#64748B',
    line: '#D8E2EA',
    paper: '#F8FAFC',
    warmPaper: '#FFF8ED',
    white: '#FFFFFF',
    glassDark: 'rgba(15,23,42,0.72)',
    glassLight: 'rgba(255,255,255,0.72)',
    glassBorder: 'rgba(255,255,255,0.34)',
    cyanWash: '#ECFEFF',
    pinkWash: '#FDF2F8',
    amberWash: '#FFFBEB',
  },
  radius: {
    card: 8,
    hud: 12,
    control: 10,
    chip: 999,
    polaroid: 4,
  },
  space: {
    xxs: 4,
    xs: 6,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
  },
  type: {
    sportNumber: {
      fontWeight: '900' as const,
      fontStyle: 'italic' as const,
      letterSpacing: 0,
    },
    label: {
      fontWeight: '900' as const,
      letterSpacing: 0,
      textTransform: 'uppercase' as const,
    },
    body: {
      fontWeight: '700' as const,
      letterSpacing: 0,
    },
  },
  shadow: {
    glass: {
      shadowColor: '#0B1220',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.18,
      shadowRadius: 24,
      elevation: 8,
    },
    editorial: {
      shadowColor: '#0B1220',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.12,
      shadowRadius: 18,
      elevation: 5,
    },
  },
} as const;

export const NeoRouteColors = {
  planned: NeoOutdoors.color.electricCyan,
  completed: NeoOutdoors.color.deepCyan,
  offRoute: NeoOutdoors.color.adventurePink,
  diarySpot: NeoOutdoors.color.sunsetAmber,
} as const;

export const NeoOutdoorStyles = StyleSheet.create({
  glassHud: {
    ...NeoOutdoors.shadow.glass,
    backgroundColor: NeoOutdoors.color.glassDark,
    borderColor: NeoOutdoors.color.glassBorder,
    borderRadius: NeoOutdoors.radius.hud,
    borderWidth: 1,
  },
  sunsetGlassHud: {
    ...NeoOutdoors.shadow.glass,
    backgroundColor: 'rgba(255,248,237,0.78)',
    borderColor: 'rgba(245,158,11,0.34)',
    borderRadius: NeoOutdoors.radius.hud,
    borderWidth: 1,
  },
  editorialCard: {
    ...NeoOutdoors.shadow.editorial,
    backgroundColor: NeoOutdoors.color.white,
    borderColor: 'rgba(216,226,234,0.82)',
    borderRadius: NeoOutdoors.radius.card,
    borderWidth: 1,
  },
  editorialSurface: {
    backgroundColor: NeoOutdoors.color.warmPaper,
    borderColor: 'rgba(245,158,11,0.18)',
    borderRadius: NeoOutdoors.radius.card,
    borderWidth: 1,
  },
  routeBadge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: NeoOutdoors.color.cyanWash,
    borderColor: NeoOutdoors.color.electricCyan,
    borderRadius: NeoOutdoors.radius.chip,
    borderWidth: 1,
    flexDirection: 'row',
    gap: NeoOutdoors.space.xs,
    minHeight: 28,
    paddingHorizontal: NeoOutdoors.space.md,
    paddingVertical: NeoOutdoors.space.xs,
  },
  routeBadgeText: {
    color: NeoOutdoors.color.deepCyan,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
  },
  detourBadge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: NeoOutdoors.color.pinkWash,
    borderColor: NeoOutdoors.color.adventurePink,
    borderRadius: NeoOutdoors.radius.chip,
    borderWidth: 1,
    flexDirection: 'row',
    gap: NeoOutdoors.space.xs,
    minHeight: 28,
    paddingHorizontal: NeoOutdoors.space.md,
    paddingVertical: NeoOutdoors.space.xs,
  },
  detourBadgeText: {
    color: NeoOutdoors.color.adventurePink,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
  },
  polaroidFrame: {
    ...NeoOutdoors.shadow.editorial,
    backgroundColor: NeoOutdoors.color.white,
    borderColor: 'rgba(216,226,234,0.9)',
    borderRadius: NeoOutdoors.radius.polaroid,
    borderWidth: 1,
    padding: NeoOutdoors.space.xs,
    paddingBottom: NeoOutdoors.space.lg,
  },
  polaroidImage: {
    backgroundColor: NeoOutdoors.color.line,
    borderRadius: NeoOutdoors.radius.polaroid,
    overflow: 'hidden',
  },
  polaroidCaption: {
    color: NeoOutdoors.color.ink,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 15,
    marginTop: NeoOutdoors.space.xs,
  },
  floatingControl: {
    ...NeoOutdoors.shadow.glass,
    alignItems: 'center',
    backgroundColor: NeoOutdoors.color.glassDark,
    borderColor: NeoOutdoors.color.glassBorder,
    borderRadius: NeoOutdoors.radius.control,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
    minWidth: 42,
  },
});
